renv::install("tidyverse")
renv::install("shiny")
renv::install("tidylog")
renv::install("languageserver")
renv::install("rmarkdown")
renv::install("data.table")
renv::install("furrr")
renv::install("gghighlight")
renv::install("DT")
renv::install("scales")
renv::install("ggrepel")
renv::install("patchwork")
renv::install("geosphere")
renv::install("quarto")
renv::install("here")
renv::install("rsconnect")


rsconnect::writeManifest()
